---
engine: julia
execute:
  cache: true
mainfont: Lato
format:
  agil_stcalc_template-typst: default

company: Agilitus
client: BWN Services
proj_no: 25229
proj_title: GOODMAN FIELDER ACCESS SYSTEM
calc_no: 25229-ST-CAL-0001
calc_title: Walkway Structural Design
proj_phase: Detailed Design
logo_company: "images/logo-agilitus.png"
logo_client: "images/logo-client.png"
revisions:
- rev_no: A
  rev_date: 16/01/2026
  rev_desc: IFIR
  rev_prep: Josua A
  rev_check: F. Hakim
  rev_app:  
---


```{=typst}
#like_header("Calculation Objective / Scope")
```
* Design the walkways

```{=typst}
#like_header("Calculation Assumptions")
```
* 2.5kPa live load

```{=typst}
#like_header("Software Used")
```
* Space Gass / Strand7 / RFEM, your packages here....
* Quarto / Julia  for documentation

```{=typst}
#like_header("Holds")
```
* n/a

{{< pagebreak >}}

```{=typst}
#block(above: 2em, below: 2em)[
    #outline(
      title: [Table of Contents],
      depth: 2,
      indent: auto
    );
    ]
```

{{< pagebreak >}}

```{julia}
#| label: Usings

import Pkg
Pkg.activate(".")

using Unitful, Unitful.DefaultSymbols
using MyUnits
```


# Introduction {#sec-intro}

## Calculation Objective / Scope

This calculation covers the design of the structural steel and foundation for the XXX.

The structural steel consists of three individual sub-structures isolated to control vibrations. These buildings are all braced framed systems and columns are considered pinned base.

Foundations are either combined or individual spread reinforced concrete footings.

In addition to the main structural framing, the calculation verifies the structural adequacy of:									

* Footings including hold down bolts									
* Mechanical frames and equipment plinths
* Associated chute-work and chute supports

## Exclusions
This calculation excludes the following:

* Design of the process / mechanical function for items where structural design has been completed, e.g. chutes, hoppers
* Structural design of vendor supplied equipment

## Basis of Design									

This calculation has been completed in accordance with XXXX. The Basis of Design for this calculation is described in XXXX, with mechanical load data in accordance with the XXXX.

## Design Standards and Codes
Unless specifically noted, the design complies with Australian Standards and selected international standards as listed in the Design Criteria. The following summarises the key standards used in producing this calculation:

* AS 1170.0 - 2002		Structural design actions - Part 0: General principles
* AS 1170.1 - 2002		Structural design actions - Part 1: Permanent, imposed and other actions
* AS 1170.2 - 2021		Structural design actions - Part 2: Wind actions
* AS 1170.4 - 2007		Structural design actions - Part 4: Earthquake Actions in Australia
* AS 3600 - 2018		Concrete structures
* AS 4100 - 1998		Steel structures

## Other Reference Documents

Other reference documents used in this design include:

* Geotechnical Report
* Certified Vendor Drawings

{{< pagebreak >}}

# Assumptions

## Holds

## Assumptions

## Relied on Information

{{< pagebreak >}}

# Drawings
This calculation covers the structural components on the drawings and/or sketches listed in the following table:	

|Drawing Number|Drawing Title| Revision |
|---------|----------|----------|
|0001|General Arrangement|A|
|0002|Details 1|0|
|0003|Details 2|C1|
|0004|Earthworks|x|
: {tbl-refdwgs tbl-colwidths="[20,70,10]"}

{{< pagebreak >}}

# Methodology, Loading and Load Combinations
Do some calculation here.
